title: ackwell.
description: >-
  description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: null

permalink: /:title
collections:
  posts:
    permalink: /:collection/:title

sass:
  style: compressed
